# collections
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header_feature_image:
    caption:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    header_feature_image:
    caption:
- scope:
    path: ''
    type: recipe
  values:
    layout: recipe
    order:

# SITE CONFIGURATION
baseurl: ''  #leave this alone
url: "https://water-oxide.github.io"   #change this to yours DONE
title: The Tempest: E-Book # site's title DONE
description: "Read Shakespeare, The Tempest" # used by search engines DONE

# SITE-SPECIFIC CONFIGURATION
# Change these 2 images for your own site

avatar: assets/img/face.jpg assets assets/img/riker.jpg
favicon: assets/favicon.ico

# Your blog on the home page can be arranged as a grid

gridlayout: false # change to true if you want grd layout


# Header and footer text
# Change this text to yourown DONE
header_text: "Shakespeare's greatest play"

# find an image for your own home page and put it into the images folder DONE
header_feature_image: /play_cover_multi-media_module.jpg /assets/img/mount.jpeg

twitter_username:   #change to your own twitter account
lang: en_gb
# change the following to your name or site name DONE
footer_text:
    "Copyright 2020 Dan_18040611"
  # Icons
  # If you have any of these accounts add them in here
rss: false  # Make sure you created a feed.xml with feed.xml layout
email_address: 18040611@brookes.ac.uk
facebook:
flickr:
google_plus:
instagram:
linkedin:  # Full URL
pinterest:
soundcloud:
twitter: # "twitter username"
youtube:

# Sharing options
share_buttons:
  facebook: true
  twitter: true
  tumblr:
  pinterest:
  linkedin:
  email: true

# Scripts / Features
google_analytics: # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: # create an account on disqus.com for comments

# Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_share_on: "Share on"
str_add_to: "Add to"
str_email: "Email"
str_tweet: "Tweet"
str_pin_it: "Pin it"
str_next_post: "Next post"
str_previous_post: "Previous post"
str_next_page: "Next"
str_previous_page: "Prev"
str_javascript_required_disqus: "Please enable JavaScript to view comments."

# Post navigation
post_navigation: true

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
exclude: [".jekyll-cache", "Gemfile", "README.md"]
